import { ElementRef, EventEmitter, OnInit, AfterViewInit } from '@angular/core';
export declare class StickyComponent implements OnInit, AfterViewInit {
    private element;
    zIndex: number;
    width: string;
    offsetTop: number;
    offsetBottom: number;
    start: number;
    stickClass: string;
    endStickClass: string;
    mediaQuery: string;
    parentMode: boolean;
    orientation: string;
    activated: EventEmitter<{}>;
    deactivated: EventEmitter<{}>;
    reset: EventEmitter<{}>;
    private isStuck;
    private elem;
    private container;
    private originalCss;
    private windowHeight;
    private containerHeight;
    private elemHeight;
    private containerStart;
    private scrollFinish;
    constructor(element: ElementRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    onChange(): void;
    defineOriginalDimensions(): void;
    defineDimensions(): void;
    resetElement(): void;
    stuckElement(): void;
    unstuckElement(): void;
    matchMediaQuery(): any;
    sticker(): void;
    private scrollbarYPos();
    private getBoundingClientRectValue(element, property);
    private getCssValue(element, property);
    private getCssNumber(element, property);
}
